[project]
name = '4v4'
description = '3D NFT Market'
authors = []
telemetry = true
cache_dir = './.cache'

[accounts.deployer]
mnemonic = "prison help inch era stage soon raise despair burger advice empty shift flight stand keep index symptom waste shrimp assist north warm again zoo"

[contracts.claim]
path = 'contracts/claim.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
